base_url = "https://resume.marzoog.co"
compile_sass = true
title = "Marzoog"
description = "Marzoog AlGhazwi Resume"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Marzoog"
last_name = "AlGhazwi"
address = "Eastern Province, Saudi Arabia"
email = "marzoog.m.alghazwi@gmail.com"
favicon = "/eimad.ico"
avatar = "/media/marzoog-p.JPG"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = false
show_publications = false
show_experience = true
show_education = true
show_blog = false
